# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17.19
fabric_version=0.157.0+26.2

# UI deps
sgui_version=2.1.0+26.2
clothconfig_version=26.2.155
modmenu_version=20.0.1
groovy_version=5.0.7

# Mod Properties
mod_version=1.0.0-26.2
maven_group=com.flwolfy.starrylist
archives_base_name=the-starry-list
